server_port: 4000
url: http://nossograndedia.com
title: "nossograndedia.com"
description: "..."
logo: #"/images/logo.png"
permalink: date
author:
    name: "David & Alice Joos"
    email: davidandalice@nossograndedia.com
sitemap:
    changefreq: daily
    priority: 0.5
    page:
        changefreq: monthly
        priority: 0.5
google-analytics:
    account: UA-4871859-1
jwplayer:
    key: "Rj7goVioVu7HkzMpDxW9gdjuXSihGJINsjJafw=="